config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :articles
  resources :categories
  root 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
   validates :name, presence: true, length: {minimum: 3, message: 'Name must at least contain 3 letters'}
   validates :img, presence: {message: 'must have url for example: https://cdn.wallpapersafari.com/9/92/cCw4WK.jpg'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :score_sum, :score_amount, :read_time, :date)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @best = Article.last(5).reverse
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :img)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.last(15).reverse 
    @best = Article.last(5).reverse
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

   private

   def sign_up_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
   end

   def account_update_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
   def format_date(date)
      month = date.month
      day = date.wday
      year = date.year
      month_name = Date::MONTHNAMES[month]

      return "#{month_name} #{day}, #{date.year}"
   end

   def cut_content(text)
      return "#{text[0..100]} #{text.length > 100 ? "..." : ""}"
   end

   def articles_amount(number)
      if(number > 9999999999999999) 
         return "#{9999999999999999} +"
      else
         number
      end
   end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :score_sum %>
    <%= f.input :score_amount %>
    <%= f.input :read_time %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Score sum</th>
      <th>Score amount</th>
      <th>Read time</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.score_sum %></td>
        <td><%= article.score_amount %></td>
        <td><%= article.read_time %></td>
        <td><%= article.date %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Score sum:</strong>
  <%= @article.score_sum %>
</p>

<p>
  <strong>Score amount:</strong>
  <%= @article.score_amount %>
</p>

<p>
  <strong>Read time:</strong>
  <%= @article.read_time %>
</p>

<p>
  <strong>Date:</strong>
  <%= @article.date %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= stylesheet_link_tag "categories" %>

<div class='categories'>
	<main>
		<h2>CATEGORIES</h2>
		<%= link_to new_category_path do %>
			<button class='add-btn'>
				<i class="fas fa-folder-plus"></i>
				<p>Add Category</p>
			</button>
		<% end %>
		<div class='list'>
			<% @categories.each do |category| %>
				<div class="category">
					<div class='category__img' style="background-image: url('<%= category.img %>');"></div>
					<div class='category__name'>
						<%= category.name %>
						<div class='category__links'>
							<%= link_to category, class: 'link' do %>
								<i class="fas fa-external-link-alt" style="margin: 0 10px 0 0; color: white"></i>
								<p>Enter</p>
							<% end %>
							<%= link_to category, data: { confirm: 'Are you sure?' }, method: :delete, class: 'link delete' do %>
								<i class="fas fa-folder-minus" style="margin: 0 10px 0 0; color: white; font-size: 18px"></i>
								<p>Delete</p>
							<% end %>
						</div>
					</div>	
				</div>
			<% end %>
		</div>
	</main>
	<%= render 'shared/aside' %>
</div>

app/views/categories/new.html.erb
<%= stylesheet_link_tag "form" %>

<div class='wrapper register'>
	<%= simple_form_for(@category) do |f| %>
		<div class="wrapper__form">
         <%= f.error_notification %>

			<h2 class='wrapper__header'>NEW CATEGORY</h2>

			<% if @category.errors.any? %>
				<div id="error_explanation">
					<div class='alert'>
						<% @category.errors.full_messages.each do |msg, index| %>
							<p class='error'><%= msg %></p>
						<% end %>
					</div>
				</div>
			<% end %>
			
			<div class='field'>
				<%= f.input :name, :error => false,
					required: true,
					autofocus: true,
					wrapper: false,
					label: 'Name:',
					input_html: { class: "input"},
					label_html: { class: "label" }
				%>
			</div>
			
			<div class='field'>
				<%= f.input :img, :error => false,
					required: true,
					wrapper: false,
					label: 'Img Url:',
               placeolder: 'For example: https://cdn.wallpapersafari.com/9/92/cCw4WK.jpg',
					input_html: { class: "input textarea"},
					label_html: { class: "label" }
				%>
			</div>

			<div class="form-actions">
				<%= f.button :submit, "CREATE", class: "button" %>
            <%= link_to categories_path, class: 'back-btn' do %>
               <i class="fas fa-undo-alt"></i>
               <p>BACK</p>
            <% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<%= stylesheet_link_tag "root" %>

<% @articles.each_with_index do |article, index| %>
   <% if index == 0 %>
      <div class='newest'>
         <div class='newest__cover'>
            <div class='newest__content'>
               <%# Później to będzie article.category %>
               <p class='content__category'>FASHION</p>
               <p class='content__title'> <%= article.title %>  </p>
               <p class='content__date'> <%= format_date(article.created_at) %> </p>
            </div>
         </div>
      </div>
   <% end %>
<% end %>
<div class='row'>
   <% @articles.each_with_index do |article, index| %>
      <% if index.between?(0,2) %>
         <div class='row__article'>
            <div class='article__cover'>
               <div class='content'>
                  <%# Później to będzie article.category %>
                  <p class='content__category first-three'>SPORT</p>
                  <p class='content__title content__title--small'> <%= article.title %>  </p>
                  <p class='content__date content__date-small'> <%= format_date(article.created_at) %> </p>
               </div>
            </div>
         </div>
      <% end %>
   <% end %>
</div>
<%# zrobić tutaj div, który będzie podzielony na dwie części w proporcji 70% do 30% %>
<%# 70% będzie zawierać iterację i zwracać najlepszy post z każdej możliwej kategorii %>
<%# 30% to będzie jako fixed 5 najlepszych postów z wszystkich kategorii oraz 5 kategorii z największą ilością postów %>
<section class='section'>
   <main class='main'>
      <h2 class='main__header'>The Best Of Categories</h2>
      <div class='main__articles'>
         <% @articles.each_with_index do |article, index| %>
            <div class="article">
               <div class='cover'>
                  <div class='cover__content'>
                     <p class='content__category--small'>RUNNING</p>
                     <p class='content__title content__title--small'><%= article.title %></p>
                     <p class='content__description'><%= cut_content(article.content) %></p>
                  </div>
               </div>
            </div>
         <% end %>
      </div>
   </main>
   <%= render 'shared/aside' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	 <script src="https://kit.fontawesome.com/8253b0ed7b.js" crossorigin="anonymous"></script>
  </head>

  <body>
	<nav class='navbar'>
		<h1 class='navbar__brand'>VLOG</h1>
		<div class="navbar__links">
			<%= link_to 'HOME', root_path, :class => 'navbar__links__link' %>
			<%= link_to 'CATEGORIES', categories_path, :class => 'navbar__links__link' %>
			<%= link_to 'ABOUT US', root_path, :class => 'navbar__links__link' %>
			<% if !user_signed_in? %>
				<%= link_to 'CREATE ACCOUNT', new_user_registration_path, :class => 'navbar__links__link' %>
				<%= link_to 'LOGIN', new_user_session_path, :class => 'navbar__links__link' %>
			<% else %>
				<%= link_to "LOG OUT", destroy_user_session_path, method: :delete, :class => 'navbar__links__link' %>
			<% end %>
		</div>
	</nav>
	<div class="navbar-burger burger" data-target="navbar">
		
	<div class='container'>
		<%= yield %>
	</div>

	<footer>
		<p>VLOG</p>
		<div class="navbar__links--footer">
			<%= link_to 'HOME', root_path, :class => 'navbar__links__link' %>
			<%= link_to 'CATEGORIES', categories_path, :class => 'navbar__links__link' %>
			<%= link_to 'ABOUT US', root_path, :class => 'navbar__links__link' %>
			<% if !user_signed_in? %>
				<%= link_to 'CREATE ACCOUNT', new_user_registration_path, :class => 'navbar__links__link' %>
				<%= link_to 'LOGIN', new_user_session_path, :class => 'navbar__links__link' %>
			<% else %>
				<%= link_to "LOG OUT", destroy_user_session_path, method: :delete, :class => 'navbar__links__link' %>
			<% end %>
		</div>
		<p class='copyright'>@Copyright Dawid Łychoński 2020</p>
	</footer>
  </body>
</html>

app/views/shared/_aside.html.erb
<%= stylesheet_link_tag "_aside" %>

<aside class='aside'> 
   <h2 class='aside__header'>Most Popular Posts</h2>
   <div class='popular'>
      <% @best.each_with_index do |article| %>
         <div class="wrapper__article">
            <div class='article__img'></div>
            <div class='content--aside'>
               <div class='article__info'>
                  <div class='info__date'>
                     <i class="far fa-calendar"></i>
                     <span><%= format_date(article.created_at) %></span>
                  </div>
                  <div class="info__owner">
                     <i class="far fa-user"></i>
                     <span>Admin</span>
                  </div>
               </div>
               <p class='article__title'><%= article.title %></p>
            </div>
         </div>
      <% end %>
   </div>
   <div class='biggest'>
      <h2 class='aside__header'>The Biggest Categories</h2>
      <div class="box">
         <div class='element'>
            <p>FASHION</p>
            <p><%= articles_amount(45) %></p>
         </div>
         <div class='element'>
            <p>SPORT</p>
            <p>28</p>
         </div>
         <div class='element'>
            <p>RUNNING</p>
            <p>24</p>
         </div>
         <div class='element'>
            <p>MOVIES</p>
            <p>24</p>
         </div>
         <div class='element'>
            <p>FOOD</p>
            <p>21</p>
         </div>
      </div>
   </div>
</aside>